package com.monitoring.microservices.service.registry.exception

enum class ErrorCode {
    ERR_INCONSISTENT_INSTANCE_STATE_EXCEPTION,
    ERR_INSTANCE_UNAVAILABLE_NOW_EXCEPTION,
    ERR_NOT_FOUND_FREE_INSTANCE_EXCEPTION,
    ERR_SAVE_INSTANCE_TO_DB_EXCEPTION,
    ERR_FIND_FREE_INSTANCE_EXCEPTION,
    ERR_REGISTRY_INSTANCE_TARGETS_EXCEPTION
}
